resource "aws_iam_role" "role" {
  count                 = var.enabled ? 1 : 0
  name                  = var.name
  assume_role_policy    = var.assume_role_policy
  path                  = var.path
  description           = var.description
  max_session_duration  = var.max_session_duration
  force_detach_policies = var.force_detach_policies
  tags                  = var.tags
}

resource "aws_iam_policy" "user_policies" {
  name        = "${var.name}Policy-${count.index}"
  path        = var.path
  description = "User-managed policy assigned to the ${var.name}Role role (generated by Terraform)"
  policy      = var.policy_jsons[count.index]
  count       = length(var.policy_jsons)
}

resource "aws_iam_role_policy_attachment" "user_policies" {
  role       = join("", aws_iam_role.role.*.name)
  policy_arn = element(aws_iam_policy.user_policies.*.arn, count.index)
  count      = length(var.policy_jsons)
}

resource "aws_iam_role_policy_attachment" "attached_policies" {
  role       = join("", aws_iam_role.role.*.name)
  policy_arn = var.policy_arns[count.index]
  count      = length(var.policy_arns)
}

# Conditionally creating instance profile
resource "aws_iam_instance_profile" "instance_profile" {
  count = var.create_instance_profile ? 1 : 0
  name  = "${var.name}-instance-profile"
  role  = aws_iam_role.role.name
  path  = var.path
}
